### ISSUE TITLE
phantomjs2 fails to build on OSX

### ISSUE THREAD

**Issue by dmjio** [dmjio/miso#160]
This just means tests won't build on OSX.

Possible solutions:
  - Use `chrome --headless` instead (if it builds on both darwin & linux)
  - Fix `phantomjs2` derivation

**Comment by alexeyzab** [comment]
Hi there! Would you be interested in providing some mentorship/general help on resolving this so that the newcomers and first-time contributors would have an easier time?

I would like to add this as one of the issues for the upcoming [Haskell Weekly's](https://github.com/haskellweekly/haskellweekly.github.io) Call for Participation section. See discussion in [#75](https://github.com/haskellweekly/haskellweekly.github.io/issues/75).

These are the guidelines we'd like to stick to in the future:
* Ensure that your project has at least one open-source licence. (we've decided to not define the term "open-source" and it is left to your own interpretation).
* Ensure that the issue tracker for your project is publicly accessible.
* Create a new issue in your issue tracker and clearly describe the task. Also mention the difficulty level (easy/medium/hard/tedious), either as a tag/label or somewhere in the title/description.
* If you have specific requirements for contributors (e.g., copyright waiver), it must be mentioned in the description of the task (preferably with a link to CONTRIBUTING.md).

Alternatively if you think there's a more suitable issue for mentioning in the CFP, let me know.

Thank you!

**Comment by dmjio** [comment]
Hi @alexeyzab, apologies this issue is a little under specified. The issue tracker should provide  more clarity in general. Some of these issues are acting as informal todo's. I think providing more context will definitely spur on contributors. I've been a bit jammed with things at work, but I'm planning no releasing large updates to the `README.md` and also `Contributors.md` this weekend. 

In regards to this specific issue, there is a way to bypass this issue (by commenting out out `checkPhase` in `default.nix`). This will allow the project to be built on OSX (under `nix`)  although, without tests. This is a temporary workaround until I can fix this issue on https://github.com/nixos/nixpkgs itself.

In regards to the bullet points.

- We have a `BSD3` license
- Issue tracker is public
- The issues aren't always clear and the difficulty isn't specified (that also might be a relative metric). -- For example, the dev ops tags assume `nix` development experience. So we might need to cover the basics of that as well.
- `CONTRIBUTING.md` is a task I have defined, and plan on creating this weekend.

There might be other issues that are better to chop off first. This project honestly got released a little early and I didn't have adequate time to document. I think submitted a CFP should occur after the README has been updated, along with CONTRIBUTING.md, which again, should be done this weekend. This will provide better context for the project as a whole, and a deeper understanding of the implementation and design choices.

**Comment by alexeyzab** [comment]
Hi @dmjio, thanks for a quick reply! I understand, if there are any other issues you'll need help with in the future, on any of your Haskell projects, let me know and I'll include them in the newsletter.

**Comment by dmjio** [comment]
@alexeyzab awesome, absolutely.

**Comment by dmjio** [comment]
related: https://github.com/NixOS/nixpkgs/issues/22172

**Comment by dmjio** [comment]
Tests have been disabled on Darwin due to this.
