### ISSUE TITLE
Newbie issue: How to setup an editor (intero, preferably)?

### ISSUE THREAD

**Issue by saurabhnanda** [dmjio/miso#220]
So, I'm pretty excited about Miso and even got the example in the README working within no time (apart from the extremely long GHCJS boot, that is!)

I'm wondering how you've setup your editors to work with GHC **and** GHCJS together. I'm using Intero and it just [doesn't work with GHCJS projects (known issue)](https://github.com/commercialhaskell/intero/issues/64) I tried changing my stack & cabal files [1] to use GHC along with [ghcjs-base-stub](https://hackage.haskell.org/package/ghcjs-base-stub), but that throws off Miso, which starts using the [GHC version of the Miso package](http://hackage.haskell.org/package/miso-0.4.0.0) [2]

What's the easiest way to hop back & forth while editing the server code (GHC) and client code (Miso/GHCJS)?

[1] to attempt a workflow where the editor uses GHC and when everything compiles, I generate the JS assets via the command line using a slightly different stack & cabal file.
[2] I'm assuming that is what is happening here, because it is no longer able to find `App` and `Effect` types.

**Comment by dmjio** [comment]
This is a great point, and an oversight in the documentation (workflow). My dev. workflow is primarily with `nix` (specifically `nix-shell`). I usually generate two `nix` scripts `server.nix` and `client.nix`, then combine them into a file named `default.nix`. From here I can just call `nix-shell -A server.env` and I'll be in a shell with `ghc`, likewise for the client `nix-shell -A client.env`, and I'll be in a shell w/ `ghcjs`. After this, one must call `cabal configure --ghcjs` (unless you have `compiler: ghcjs`) inside your `cabal.config` file -- assuming you're in the `client` environment. I then open up emacs `haskell-mode` and begin editing. If I want to change to the server code, I exit emacs, call `cabal configure --ghc` and then open up a new emacs. (Exiting isn't necessary, you could just terminate the `interactive` session as well). 

So, with `stack` I imagine you could do similar. Instead of calling `nix-shell`, you could call `stack exec --yaml-file server.yaml`, and then be in a shell with the correct compiler, dependencies. You might have to call `cabal configure` from here (I'm not entirely sure how to configure things with stack tbh).

Let me know if this has helped, or if you need more. But we should document all of this for others.

**Comment by dmjio** [comment]
re:`ghcjs-base-stub`, interesting I've never seen this package, I'll have to try it.

**Comment by 3noch** [comment]
@dmjio I think @saurabhnanda was hoping for Intero compatibility for the front-end code. When using `reflex-dom`, for example, one can use `intero` because all of the reflex-* libraries uses `jsaddle` and therefore compiles with both GHC and GHCJS almost exactly the same.

@saurabhnanda Since you can't use `intero` with GHCJS, you'll need to use something like `haskell-mode` for emacs or `ghcid` when working on the front-end with Miso. I think this is something that @dmjio and co. will likely try to fix in the future.

**Comment by cocreature** [comment]
fwiw I’ve actually startet [working](https://github.com/cocreature/miso/tree/jsaddle) on integrating `miso` with `jsaddle`. It’s not yet in a working state and I can’t make any promises when or if it will be finished but I’m more than happy to collaborate on it.

**Comment by saurabhnanda** [comment]
> re:ghcjs-base-stub, interesting I've never seen this package, I'll have to try it.

Is there any way to force miso to use the GHCJS version of the package even when it is being compiled with GHC? This way it can work with Intero and `ghcjs-base-stub` -- at least I can give it a try.

**Comment by dmjio** [comment]
@saurabhnanda, was thinking exactly this as well. Will try to see what this would look like. Might be the quickest, lightweight option.

**Comment by saurabhnanda** [comment]
@3noch 

> you'll need to use something like haskell-mode for emacs or ghcid when working on the front-end with Miso.

Do you know how to get `ghcid` working with stack+ghcjs? I'm running into the following problem:

```
Saurabhs-MacBook-Pro:miso-ghcjs-keyed saurabhnanda$ stack install ghcid
Couldn't find executable ghcid in directory /Users/saurabhnanda/.stack/snapshots/x86_64-osx/lts-7.19/ghcjs-0.2.1.9007019_ghc-8.0.1/bin/
```

**Comment by 3noch** [comment]
@saurabhnanda You may need to install `ghcid` globally so that it doesn't get treated like a GHCJS package.

**Comment by polux** [comment]
Hello, did someone manage to get miso to work with `ghcjs-base-stub` after all?

**Comment by dmjio** [comment]
hey @polux, `miso` was written using vanilla emacs, haskell-mode and `GHCJSi` (for REPL). I've never used `intero`. Does your setup include `intero`?

**Comment by polux** [comment]
I don't mind using something else than intero (HIE is fine for instance, it's actually probably better for me because I'd like to use nix instead of stack) but I appreciate having things like "type of expression", "insert type signature" and "hilight errors in buffer" when programming in haskell. Before intero and HIE, I used to have that using https://github.com/lukerandall/haskellmode-vim, maybe that would work with ghcjs. I also don't mind using emacs if you have something similar to recommend.

**Comment by dmjio** [comment]
@polux, sure, personally I've never used `haskellmode-vim`, but have heard good things. I'm sure it has a "send to REPL" command (like `C-x C-l` for haskell-mode emacs).
