### ISSUE TITLE
Browsing haskell-miso.org with JS disabled

### ISSUE THREAD

**Issue by rihardsk** [dmjio/miso#241]
It would be great if [haskell-miso.org](https://haskell-miso.org) worked the same with JS disabled. Which would also be a great showcase for the _isomorphic_ feature.

It seems that the only thing not functioning correctly with JS disabled are the top navigation controls. Adding a `href` attribute and `onclick="return false;"` solves this, but maybe there is a more idiomatic way to do this?

**Comment by dmjio** [comment]
Fantastic idea. So it seems if the user had js enabled that we'd like navigation to occur with the pushState API, and prevent the default behaviour of navigation by way of the href tag.  So in order to support this we'd need to put both a click handler with options that preventDefault behaviour from occurring, and a href attribute on the a tag. This will give correct behaviour under both scenarios. 
```
a_ [ href "/about"
     , onClick defaultOptions { preventDefault = True } $ goAbout
     ] [ ]
```
