### ISSUE TITLE
Useful misc functions

### ISSUE THREAD

**Issue by FPtje** [dmjio/miso#308]
There are a couple of functions that keep coming back in my projects. Would it be a good idea to have some variant of them in miso by default?

One of them may have some trouble with isomorphism. Perhaps there is a better alternatives available?

```haskell
-- | Define a view per element of some Foldable
withFoldable
    :: (Foldable t)
    => t a
    -> (a -> View action)
    -> [View action]
withFoldable ta f = reverse $ foldl' (\v a -> f a : v) [] ta

-- | Optional view, does not show when predicate is false
-- May conflict with isomorphic js if you have multiple of them in a row
optionalView :: Bool -> View action -> View action
optionalView b v = if b then v else text ""

-- | Disable an element based on a predicate
disableIf :: Bool -> [Attribute a]
disableIf condition =
    if condition
    then [disabled_ "true"]
    else []
```

**Comment by cocreature** [comment]
In general, I think adding some smaller helpers to simplify common patterns is a good idea! Now to your specific functions:

1. This can be generalized to `mapToList :: Foldable t => t a -> (a -> b) -> [b]` and the definition can be simplified to `mapToList ta f = map f (toList ta)` (which is also more efficient). However that’s so short that I’m not sure how useful it actually is but I’m not opposed to adding it.
2. I’ve found myself using a similar pattern a few times but I’ve chosen to go with a return type of `[View  action]` so that I can use an empty list instead of an empty text node which feels a bit like a hack. I’d probably also name this something resembling `when` since both the type signature and the behavior are very similar to that function from `base` while `optional` does something quite different.
3. Definitely seems useful although I haven’t needed it myself. Do you think it would be more useful to have this as `disableIf :: Bool -> View a -> View a`? You can’t quite implement this using the API currently exposed by `miso` but the changes required are really small so I don’t think this should be stopping us from choosing the API that’s more convenient for users.

**Comment by FPtje** [comment]
1. You're right, that does seem shorter and more efficient. There's a general pattern here that I'm importing from our other libraries. It's often used with `Maybe`s:

```haskell
view model = 
    div_ [] $
     withFoldable (model ^. mSomeMaybeVal) $ \someVal ->
        p_ [] [ text $ "Hey, look at this value: " <> ms (show someVal) ]
```

It shows nothing when the value is `Nothing`, which appears to be a common use case for us. It's really useful with lists too.

2. Yeah, a list could also be good, yeah. That would definitely solve the `text ""` thing. The name isn't ideal, I agree. `when` forces a `()` return, though, what about `conditionalView`?

3. Good thinking! Sounds good!

**Comment by dmjio** [comment]
Consider adding this to `Miso.Util`.

**Comment by FPtje** [comment]
Withe the PR merged, this issue can be closed.
