### ISSUE TITLE
Parform routing in update rather than view?

### ISSUE THREAD

**Issue by polux** [dmjio/miso#316]
The Router example shows how to use `runRoute` in the view function in order to change the view depending on the current URL, which has to be stored in the model.

I sometimes need to to handle URL changes in my update function too. For instance, let's say I'm writing an RSS reader and the URL changes to "/feeds/123/item/456". I not only want to record that I'm now looking at item 456 of feed 123 (which I could by storing the URL in the model), but I also want to trigger a download of item 456 of feed 123. That means my update function needs to parse the URL.

So far what I've gotten away with something like this:

```
updateModel (HandleURI uri) m = execute (runRoute api handlers (m & uri .~ u))
  where execute (Left _) = m <# pure gotoHome
        execute (Right handler) = handler
```

where `handlers` is a disjunction of functions which consume the parsed URLs and return an `Effect Model Action`.

I find it a bit unsatisfactory and convoluted: the only reason I'm storing and modifying the uri in the model here is because `runRoute` reads it from there. But I'm not interested in storing the URL in model: my handlers leave enough information in the model  for my view function to know what to display. In fact, storing the URL is error-prone because that information is redundant and could get out of sync with the rest of the model if I'm not careful. I am only interested in `runRoute`'s parsing and type-safe dispatching abilities. I wish it didn't rely on `HasURI` and instead would just take a URL and call the right handler.

I've searched the existing servant libraries but couldn't find one that exposes this functionality (parsing + dispatching) alone. As far as I can tell, this is only done in `servant-server` but there it is tightly coupled to the serving features. I guess this is why you had to replicate some of that code in `Router.hs`.

Do you think it would make sense for `Router.hs` to expose this functionality in a way that doesn't require the URL being stored in the model?

**Comment by cocreature** [comment]
> I am only interested in runRoute's parsing and type-safe dispatching abilities. I wish it didn't rely on HasURI and instead would just take a URL and call the right handler.

`HasURI` doesn’t actually force you to store the URI in your model, it forces you to store enough information in your model such that you can reconstruct the URI from your model and adapt your model to URI changes. The latter could be relaxed (and I’d personally prefer that) since the only time the setter functionality provided by the URI lens is actually used is during initialization. So `HasURI` could be degraded to simply providing a function `Model -> URI`. Initialization could then work by assuming that the model passed to `startApp/miso` already contains the current URI (in fact `startApp` already makes this assumption, it’s only `miso` that actually sets the URI which seems like a bug). 

You might also be interested in my [servant-match](https://github.com/cocreature/servant-match/blob/master/test/Spec.hs) library which allows you to parse an `URI` to an adt based on your servant schema. You can then simply pattern match on it and dispatch appropriately. I’m using that quite heavily for parts of `update` that depend on the current URI (mostly initialization in my case).

**Comment by polux** [comment]
> HasURI doesn’t actually force you to store the URI in your model, it forces you to store enough information in your model such that you can reconstruct the URI from your model and adapt your model to URI changes.

That's right. This solves the redundancy issue. But it doesn't help with the other issue, namely that I'd like to react to URI changes in the update method while benefiting from runRoute's URL parsing and type-safe dispatching.

> You might also be interested in my servant-match library which allows you to parse an URI to an adt based on your servant schema.

Great! That's exactly what I was looking for.

I don't know if I should close this issue though: I think this style (reacting to URI changes in update) should be the default, as one can easily recover the current style from it while the reverse doesn't hold.

**Comment by cocreature** [comment]
> I don't know if I should close this issue though: I think this style (reacting to URI changes in update) should be the default, as one can easily recover the current style from it while the reverse doesn't hold.

I tend to disagree although I’m not quite sure what style you have in mind. I have a reasonably large app with an action type consisting of tens of (nested) constructors. In my `update` function only a small number of cases (< 10%) actually are dependent on the route. I’d rather introduce the additional complexity in those few cases than complicate all other cases by having to work around URI dependent updates (here’s where I’m not entirely sure how that would look like in your style).

**Comment by polux** [comment]
Ok, I think what I meant is: the current type of `runRoute` makes it awkward to use in the update function because it takes a model that has a a `HasURI` instance instead of just a URI. In order to use it you first need to patch the model to include the new URI and then call `runRoute`. This also forces you to store the actual URI in the model instead of some information it can be reconstructed from, because that information can sometimes only be derived from the new URI, which hasn't been parsed yet.

If I understand correctly, the reason `runRoute` takes a model is not because it couldn't be rewritten to take a URI, but because it makes it more convenient to use in the view function. It saves its caller from extracting the URI from the model themselves.

My point is that this convenience doesn't justify the awkwardness of calling `runRoute` in the update function by first patching the model.

**Comment by dmjio** [comment]
`HasURI` has been removed. It is no longer necessary to store the `URI` on the `model`. Routing for pages should occur in `view`, if additional routing is needed (that does not resolve to a `view`), then I'd recommend `servant-adt` as well. It seems like this issue is resolved, please re-open if necessary.

**Comment by dmjio** [comment]
@polux, yes, `servant-match`, my mistake. Given your criteria above, would it be possible to pass along the feed id and item id to `HandleURI`? This would get around needing to parse information out of the URI with `runRoute`.

```haskell
updateModel (HandleURI feedId itemId uri) m = 
  m & uri .~ u <# AjaxResult <$> ajaxCall feedId itemId 
```

This might seem redundant because the `feedId` and `itemId` were also incorporated into the `URI`, but this relieves the need to inspect the URI itself.

Going to re-open since others have asked for the ability to inspect the URI.

**Comment by polux** [comment]
If I understand your suggestion correctly, this works if the app itself was responsible for the URL change event. But what if someone navigates to `/feeds/123/item/456`? Then I'd need to parse the URL in order to extract the feed ID and item ID.

**Comment by dmjio** [comment]
Ah, I see, for initial page load this would be problematic, since the model would need to be constructed with `feedId` 123 and `itemId` 456. Would it be possible to fetch the relevant model at that URL from the server in `initialAction` or even before `startApp` is entered?

**Comment by polux** [comment]
@dmjio yes I can if I control the backend (in my case I do but I can imagine cases where I don't).

@cocreature yes, that would be my preferred option. I guess this bug/feature request boils down to: could Miso expose something akin to servant-match? It already does with `runRoute`. But runRoute has a complicated calling convention when you only need that part of the functionality.

**Comment by cocreature** [comment]
@polux I am obviously biased here but I don’t see the advantage of duplicating the functionality of `servant-match` in `miso`. The dependency footprint of `servant-match` is minimal if you’re already depending on `servant` so that can’t be the issue here.

**Comment by cocreature** [comment]
> Sure. I'm just worried that others will run into the same design issue, won't know about servant-match, and will work around the issue awkwardly.

That seems like an issue that could be solved with documentation instead of code.

> Also one potential concern is that servant-match and miso routing might be inconsistent with each other (although they should not be if servant's semantics are well defined).

I’d say that if they disagree, then one of them has a bug which can be fixed.

To be clear, I’m not suggesting that `servant-match` is some magic unicorn that will solve all problems. If there are issues that are better solved in other ways, then changing `miso` in some way may very well be the best solution! But it sounds like your current suggestion is to literally take the functionality provided by `servant-match` and duplicate it in `miso` itself with the only advantage being that it might be easier for users to discover. That just doesn’t seem like a sufficient motivation for going that route.

**Comment by dmjio** [comment]
@polux if you're using the `miso` function you can retrieve the model in json form from the same endpoint as the HTML.

Hypothetically,

```haskell
type API = "feeds" :> Capture "feedid" Int :> "items" :> Capture "itemid" Int :> Get '[Html, JSON] Model

feedHandler :: Int -> Int -> Server Model
feedHandler feedId itemId = do
  model <- getModelFromDB feedId itemId
  pure model { uri = safeUri (Proxy @ Home) (Proxy @ API) feedId itemId }

instance ToHtml Model where
  toHtml model = toHtml $ Wrapper (view model)

instance ToHtml a => ToHtml (Wrapper a) where
    toHtml (Wrapper inner) = do
       -- doctype .. toHtml inner

-- instance ToHTML (View a) already exists
```

This assumes you have a backend of course, but in cases w/o (as you alluded to), there might be a way for us to genericize the router so that it can route to any value we want (as opposed to just `View`). 

Routing builds up an intermediate ADT https://github.com/dmjio/miso/blob/master/src/Miso/Router.hs#L60

It might be as simple as changing the definition of this instance to not be specific to `View`.
https://github.com/dmjio/miso/blob/master/src/Miso/Router.hs#L126-L128.

**Comment by tysonzero** [comment]
@cocreature If you look at `Miso.Router` it appears as though `servant-match` is already almost entirely reimplemented in `miso`.

If you look at PR #389, this adds the ability to route from an arbitrary URI to an arbitrary type endpoint, and it doesn't actually create basically any new code, it's mostly just refactors and renames.

I created an [example](https://github.com/tysonzero/miso-example/tree/dd90dea83f8583d6f09dae5343b988d30826d962/client) that uses this PR to show how you can use the `URI` in updates, and how you can change the initial state / initial action based on the initial `URI`.

@polux Would this achieve what you want?

**Comment by polux** [comment]
@cocreature 

> But it sounds like your current suggestion is to literally take the functionality provided by servant-match and duplicate it in miso itself with the only advantage being that it might be easier for users to discover. That just doesn’t seem like a sufficient motivation for going that route.

Pretty much yes, except my point is that such a function already exists in Miso: it's just hidden under `runRoute`. I don't really feel strongly about it: I'm perfectly happy to depend on servant-match and whether it's part of Miso or documented is fine with me. I just find it weird to depend on some library that replicates part of Miso's functionality (`runRoute`) just because the type of `runRoute` is unnecessary constrained.

> Routing builds up an intermediate ADT [...] It might be as simple as changing the definition of this instance to not be specific to View.

Yes, something like that is what I had in mind. I think routing should now know about views or model. Instead it should only care about URIs and return-type agnostic handlers. Something like:

```
runRoute
  :: HasRouter m layout
  => Proxy layout
  -> RouteT layout a
  -> URI
  -> a
```

Notice that no more model is involved in the signature of `runRoute` or of `RouteT`.

**Comment by polux** [comment]
@tysonzero yes it looks exactly like what I was getting at!

**Comment by dmjio** [comment]
https://github.com/dmjio/miso/commit/6bf6ec1db6bfd1f6a1a1b2127465c68107d7dd44 I believe this was implemented, re-open if not so.

**Comment by tysonzero** [comment]
Yeah the new setup seems to work well. Personally I don't use the URI parameter at all in `miso`, as the server deals with the URI when creating and sending over the initial state. But for others with different setups / backwards compatibility it seems reasonable to keep it in.
