### ISSUE TITLE
Possible to compile apps via normal ghc?

### ISSUE THREAD

**Issue by h4ck3rm1k3** [dmjio/miso#323]
I guess this is a weird question but Miso.Effect is not being compiled or exposed when I compile with the ghc compiler. It seems to be only available with the ghcjs compiler. I was wondering if it might make sense to be able to compile the code as normal haskell as well? In the end we might want to also run this in a native binary with the same functionality.

**Comment by dmjio** [comment]
@h4ck3rm1k3 Great question. Here is more-or-less my philosophy for the native approach, and how I'd like to solve the trade-offs of developer time, speed, and portability (to native specifically), while being somewhat morally correct about everything:

- Developer efficiency

Obtaining `GHCJS` and using `GHCJSi` isn't ideal for efficient web development practices (albeit my experience has been pretty good, but I'm biased). To remedy this, I'd like to build something analogous to Elm's reactor or Ellie (https://ellie-app.com/), but for GHCJS development.

- Going Full Native (not just this WebView stuff)

`Miso.Effect` contains `GHCJS` specific types, so in order to compile w/ `GHC` we'd need to stub them out. One way of doing this is with `ghcjs-base-stub` package. This allows one to develop with `GHC`, but doesn't allow for viewing your app incrementally (would still need to compile w/ `GHCJS` -- not ideal). There is a project called `jsaddle` which is API-compatible w/ `ghcjs-base` and allows one to compile code natively *and* view it in the browser at the same time (sends js snippets over the wire to the browser). It is possible `miso` could use this for a better development experience. This would require `miso` to rewrite `diff.js` and `delegate.js` in Haskell. Doable, but in my opinion better solutions exist. 

Now while it is true `jsaddle` can be used to compile native apps, they only run in a WebView and do not have access to many of the APIs on the host device (afaik). So if you're hoping to gain access to all of the device, you're out of luck, and imo this is a total deal-breaker, and why `react-native` is a better solution. 

- Moral correctness

The best solution would be to somehow compile Haskell to iOS ARM, Dalvik (Android), (js / wasm) *and* somehow allow the user to have access to native APIs on all 3. This hasn't happened yet (afaik), and I'm not too optimistic it will anytime soon. The closest thing to this is Google's flutter project https://github.com/flutter/flutter which accomplishes this via Dart. Dart takes inspiration from React.js as well.

So my solution for native is pretty similar to react-native. This would mean using `jsdom` (or some other lightweight js interpreter) to run the GHCJS compiled Haskell, and do the diffing / event handling in there, making the native functions accessible inside this context as well. Then build more tooling around it.

Hope this helps!

**Comment by dmjio** [comment]
Am keeping a close eye on https://github.com/mobilehaskell though

**Comment by h4ck3rm1k3** [comment]
So as I said on chat, would it be possible to run a native haskell process on the server side that does jit compilation of the js and generates it as needed to the client?

**Comment by dmjio** [comment]
Not currently, no. This goes back to building `elm-reactor` and `ellie`, mentioned above.

> Obtaining GHCJS and using GHCJSi isn't ideal for efficient web development practices (albeit my experience has been pretty good, but I'm biased). To remedy this, I'd like to build something analogous to Elm's reactor or Ellie (https://ellie-app.com/), but for GHCJS development.

**Comment by h4ck3rm1k3** [comment]
Ok great. Thank you!
