### ISSUE TITLE
Export Miso.FFI?

### ISSUE THREAD

**Issue by osa1** [dmjio/miso#335]
I find this module really useful, I'm using `jsvalToValue` right now, but I think `now` and `consoleLog` might also be useful in a different project. Any problems with exporting it from the library?

**Comment by dmjio** [comment]
Hey! Yea, sounds like a good idea. There are some functions (like `copyDOMIntoVTree`) that I would like to keep hidden, but I'd be all for making a `Miso.Util` module in `ghcjs-src/Miso/` that re-exports `jsvalToValue`, `now`, `consoleLog` and maybe a few others. If you'd like to make a PR I'd accept. Otherwise, I can add this tonight or over weekend.

**Comment by dmjio** [comment]
https://github.com/dmjio/miso/pull/342

**Comment by dmjio** [comment]
@osa1 these new functions are now available in `0.12.0.0` 🍻

**Comment by osa1** [comment]
Thanks!
