### ISSUE TITLE
Use jsverify on tests

### ISSUE THREAD

**Issue by dmjio** [dmjio/miso#387]
Per @phadej's work, would be nice to Quickcheck `diff.js` using https://github.com/jsverify/jsverify, along with static analysis using `flow`. 

Initial work (including importing the library) is already done, importing `jsverify` and adding random generation of virtual DOM should be done in `diff.test.js`:

https://github.com/dmjio/miso/blob/master/tests/diff.test.js#L2

**Comment by dubzzz** [comment]
As the issue was pending, I tried to add some property based tests in JavaScript using `fast-check`. For the moment, I just added very simple cases. They can easily be adapted to `jsverify` if needed.

Maybe it can help you when designing the tests: https://github.com/dubzzz/miso/commit/1f470fbeafe12aa34ec6c12b3049db11f7fd945c
