### ISSUE TITLE
Input field diverging from model value

### ISSUE THREAD

**Issue by DKuhse** [dmjio/miso#578]
When a user enters a character into an input field, if the update doesn't modify the value the input field diverges from the model since its default behavior isn't suppressed and its value isn't getting reset.  

Example code:
```haskell
type Model = MisoString

data Action
  = Modify MisoString 
  deriving (Show, Eq)

updateModel :: Action -> Model -> Effect Action Model
updateModel (Modify val) m = noEff $ if Miso.String.length val <= 5 then val else m --only the value of the model gets constrained, not the value of the input field

viewModel :: Model -> View Action
viewModel m = div_ [] [
    input_ [ value_ m, onInput Modify ]
  , text m
 ]
```
In e.g. Elm an equivalent program would prevent the text in the input field from exceeding 5 characters, but the above program only restricts the model and not the input field itself.

If this is intended behavior, is there an easy way to define a custom element that behaves differently?

Edited: Corrected mistake in example

**Comment by dmjio** [comment]
What happens if you do this

```haskell
input_ [ value_ m, onInput Modify ]
```

**Comment by DKuhse** [comment]
Sorry, that's just a mistake in my example. 
[Here](https://user-images.githubusercontent.com/53220051/79929201-5e6c7f00-8445-11ea-8c3d-c5695241f5e5.png) is a screenshot of what the (corrected) example looks like for me in action.

**Comment by dmjio** [comment]
I see what's happening, in the `val > 5` case, since the model isn't changing, a redraw doesn't spawn. So the `value_` property is never updated, causing a loss of synchrony between the input element and the model state.

One thing you could do is to force the redraw by always failing the `Eq` check.

```
data Model = Model MisoString
instance Eq Model where _ == _ = False
```

This is kind of a hack. Miso's model diff check is to keep miso from generating a new tree in case something didn't update, like a preprocessing step. I don't believe redux does this check. I've contemplated its usefulness in practice. For things like scroll events that flood the event loop and have no effect on the model it is very useful to have a model check before drawing.

One thing you could do that is less hacky, but a little more manual is add a boolean that is a dirty check on that field. Then flip the value whenever modify is called.

```haskell
data Model = Model { field :: MisoString, fieldDirty :: Bool }
  deriving (Eq)

data Action
  = Modify MisoString 
  deriving (Show, Eq)

updateModel :: Action -> Model -> Effect Action Model
updateModel (Modify val) m =
  noEff m { fieldDirty = not (fieldDirty m) -- forces the update of `value`, and is local to this field
          , field = if Miso.String.length val <= 5 then val else field m
          }

viewModel :: Model -> View Action
viewModel m = div_ [] [
    input_ [ value_ m, onInput Modify ]
  , text m
 ]
```

**Comment by dmjio** [comment]
I will check out how Elm does this and get back to you..

**Comment by dmjio** [comment]
@DKuhse, In the meantime, did the suggestions I pasted above work for you?

**Comment by DKuhse** [comment]
Sadly, I haven't been able to get it working with either of them (or both combined). Even if I add a class attribute to the node, only the attribute gets updated.

If it's of any relevance, a bit of testing seems to confirm the assumption that it affects all input elements e.g. the same behavior applies to radio buttons and color pickers.

**Comment by dmjio** [comment]
@DKuhse so this case is hitting an optimization in the diffing algorithm that omits the update on the input value state (Due to the old and new DOM being equivalent). 

Given the code you pasted, if you hit the `'d'` key more than 5 times, a diff will occur each time. In the case of the 6th 'd' press, the old vdom props and new vdom props will be the same (because of the `filter` call) and the `continue` on this line of code is executed:

```js
if (newProp == cProps['value']) continue;
```

Where both `newProp` and `cProps['value']` are `"ddddd"`. `continue` is keeping the DOM from being updated. This seems like an edge case for UI elements that hold internal state like this. For now it is safe to always update the DOM in the case of receiving a `value` or `checked` diff.

https://github.com/dmjio/miso/pull/579

Note: for all other properties, we should not attempt to update the DOM if the old and new virtual dom are equivalent.

^ I would try this branch, it should contain the fix.

**Comment by dmjio** [comment]
@DKuhse let me know if this doesn't work for you, but my initial tests locally have been fruitful.

**Comment by DKuhse** [comment]
Yes, it's working great now, thank you. I'm sorry I took so long to respond, but due to my rather limited nix knowledge I at first wasn't sure how to proceed after building miso, since I was unable to find a way to point the fetch at the local library, but simply building it using cabal worked.

**Comment by dmjio** [comment]
@DKuhse glad to hear, and thanks for bringing this issue to our attention. Anything else you uncover, would be very grateful to see.
