### ISSUE TITLE
miso jsaddle is broken with 1.8 (at least in firefox)

### ISSUE THREAD

**Issue by saschaheylik** [dmjio/miso#668]
**Describe the bug**
After upgrading to 1.8, my application no longer works when trying to run with jsaddle. The GHCJS build still works. You can reproduce the bug using sample-app-jsaddle.

The bug seems to occur in Firefox but not in Chrome. Sometimes another Error is shown: "Error : Unexpected Duplicate. syncCallbacks=True nBatch=4 nExpected=6"

**To Reproduce**
1. Go to miso/sample-app-jsaddle
2. Change the tarball in the default.nix url to "https://github.com/dmjio/miso/archive/refs/tags/1.8.tar.gz".
2. run nix-shell --run reload
3. Browse to localhost:8080 to try to use the app

**Results:**
1. The app is unresponsive
2. This error is displayed in the terminal:
jsaddle missing sync message handler
CallStack (from HasCallStack):
  error, called at src/Language/Javascript/JSaddle/WebSockets.hs:129:40 in jsaddle-warp-0.9.7.0-DHMZWfEwF6AJVIaTVkQdus:Language.Javascript.JSaddle.WebSockets

**Comment by saschaheylik** [comment]
The bug seems to occur in Firefox but not in Chrome. Sometimes another Error is shown: Error : Unexpected Duplicate. syncCallbacks=True nBatch=4 nExpected=6

**Comment by dmjio** [comment]
![image](https://user-images.githubusercontent.com/875324/134032837-9c6a1ea3-aaa9-4641-b82c-df3b76a8f34c.png)

While I do see the app does become unresponsive, I'm unable to reproduce the exact error you're experiencing in the console.

```
CallStack (from HasCallStack):
error, called at src/Language/Javascript/JSaddle/WebSockets.hs:129:40 in jsaddle-warp-0.9.7.0-DHMZWfEwF6AJVIaTVkQdus:Language.Javascript.JSaddle.WebSockets
```

**Comment by dmjio** [comment]
```haskell
f x =                                                                                                                                                                                         
  onWithOptions defaultOptions { preventDefault = True }                                                                                                                                      
    "click" emptyDecoder (\() -> x)                                                                                                                                                           
                                                                                                                                                                                              
                                                                                                                                                                                              
-- | Constructs a virtual DOM from a model                                                                                                                                                    
viewModel :: Model -> View Action                                                                                                                                                             
viewModel x = div_ [] [                                                                                                                                                                       
   button_ [ onClick AddOne ] [ text "+" ]                                                                                                                                                    
 , a_ [ href_ "https://www.google.com"                                                                                                                                                        
      , f AddOne                                                                                                                                                                              
      ] [ "click me...." ]                                                                                                                                                                    
 , text (ms x)                                                                                                                                                                                
 , button_ [ onClick SubtractOne ] [ text "-" ]                                                                                                                                               
 ]  
 ```
 
 When using `asyncHandler` the above does not `preventDefault` w/ `jsaddle`.

**Comment by dmjio** [comment]
The issue is that `preventDefault` is called inside the callback function of `asyncFunction`, instead of upfront right when the event is received.

```javascript
/* event delegation algorithm */                                                                                                                                                              
window['delegate'] = function delegate(mountPointElement, events, getVTree) {                                                                                                                 
  for (var event in events) {                                                                                                                                                                 
    mountPointElement.addEventListener(events[event][0], function(e) {                                                                                                                        
      // e.preventDefault();  <------------ need to make the call here
      getVTree(function (obj) {                                                                                                                                                               
        window['delegateEvent'](e, obj, window['buildTargetToElement'](mountPointElement, e.target), []);                                                                                     
      });                                                                                                                                                                                     
    }, events[event][1]);                                                                                                                                                                     
  }                                                                                                                                                                                           
};
```

The problem is that we have no way of knowing if the user wants to call `preventDefault` at that point. Since the options of how to handle events live on VTree, and the only way of getting VTree is inside a Haskell thread. Changing the function to be synchronous does fix certain things, but breaks others (as this issue shows).

**Comment by dmjio** [comment]
Ok, so upon further inspection, `syncCallback` (in `GHCJS`) and `function` (in `jsaddle`) are the correct semantics for handling events (and calling Haskell code inside of a JS event handler). `miso` had always used this even before the transition to `jsaddle`, and even after. This was reverted (incorrectly) in the following commit https://github.com/dmjio/miso/commit/afe2536b08c7bea5267b1e7b0121c786209dcd77. This commit caused `miso` to improperly handle `preventDefault` when compiled to JS.

The fact that this doesn't work in Firefox is something to bring up with `jsaddle` / `jsaddle-warp`, not `miso`. This is working fine in Chrome and Safari, so I'd suggest you develop w/ `jsaddle` using those browsers. Furthermore, in GHCJS it works fine in all browsers.

**Comment by cdfa** [comment]
This issue has been raised with `jsaddle` a long time ago https://github.com/ghcjs/jsaddle/issues/64. I think it doesn't work on Firefox because of this even older ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=697151. Chrome also doesn't like web applications doing synchronous XHR in event handling, because it can make applications unresponsive and I think they're right.
I think there is simply no way JSaddle can let haskell code control whether `preventDefault` should be called or not or not after the event occurred without running into this.

However, I don't quite see why it would be impossible to do this if it is known beforehand whether `preventDefault` should be called or not. Actually, it seems `miso` already requires you to tell it this when defining an event handler (the `Options` argument to `onWithOptions` receives no information on the event when it occurs).
So if these options are set when rendering the element, why is it not possible to keep this information available in JS land and use it immediately when the event occurs?
If it's stored in the VTree I understand that you can not get to it, but why could it not be stored somewhere else? If you want to keep it tightly tied to the element, you could store it in a [data-attribute](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes) for example. I do think that looks a bit ugly, but it seems a viable option with my limited knowledge of `miso` internals.
