### ISSUE TITLE
miso uses an old GHCJS version that relies on git:// which was disabled on github.

### ISSUE THREAD

**Issue by fhaust** [dmjio/miso#715]
**Describe the bug**

Trying to build the `sample-app` results in a build failure. If I am not mistaken, that is due to github disabling the non-authorized git:// protocol. 

**To Reproduce**

Follow the steps [here](https://github.com/dmjio/miso#begin). 

**Screenshots**

https://gist.github.com/fhaust/033bd628fe2bc80b30b26ecfafa3135a

(I Ctrl-C'ed out of there, but the timeout just repeats several times until the whole build fails)

**Additional context**

commit 0291e869712af4ac6f2becea25eab6d023ec9980 (HEAD -> master, origin/master, origin/HEAD)

**Comment by dmjio** [comment]
Unfortunately there's not much we can do until the latest GHCJS is released (should land in GHC proper in 9.6). We stay on an old nixpkgs since its the most stable version of GHCJS. 

But, to get around the issue you've raised, did you follow the instructions and use the cachix binary cache? If you fetch from the cache you should be able to bypass all of this. Also, are you on linux or darwin?

**Comment by fhaust** [comment]
Ah ... I tried that, but it is apparently necessary to configure the trusted-users (the second option cachix suggest), I always just reran the `cachix use miso-haskell` command with `sudo`. That solves it for me :+1:

**Comment by dmjio** [comment]
Sweet, glad to hear it. Hopefully a more stable GHCJS will be available soon.
