### ISSUE TITLE
Is it ok to store sink inside the model?

### ISSUE THREAD

**Issue by functora** [dmjio/miso#750]
I need to emit action on some async events like loading files from input component:

https://github.com/functora/functora.github.io/blob/4ca33c655deea34117e27b5feb2a03f13c432c96/ghcjs/miso-functora/src/Functora/Miso/Widgets/Field.hs#L344-L350

Because my input component is basically just a view, I need to make two things - create main application miso action, and emit async event which should land on update function of the main miso application. I'm using two corresponding arguments of my input component to do so:

https://github.com/functora/functora.github.io/blob/4ca33c655deea34117e27b5feb2a03f13c432c96/ghcjs/miso-functora/src/Functora/Miso/Widgets/Field.hs#L35-L36

Providing action argument is easy - basically it's just a mapping to main miso application action type. Providing emitter argument is a bit less straightforward, because my input component is basically a view, so all argument I'm providing I should get somehow from the model, because I don't have direct access to main miso app update function, effectSub and sink. 

The workaround I'm using at the moment is to save MVar with the sink to the model on the initial main miso app update, so I can have access to it from my input component:

https://github.com/functora/functora.github.io/blob/4ca33c655deea34117e27b5feb2a03f13c432c96/ghcjs/delivery-calculator/src/Main.hs#L124-L125

Is it ok to do so, or there are better ways to emit async actions from components similar to my input component? Best regards!

**Comment by dmjio** [comment]
This isn't a bad idea per se. There really isn't a good way (that I see yet) to expose the global sink to users outside of the `update` function.

One alternative (so you can keep the model pure) is to do the `{-# NOINLINE #-}` `unsafePerformIO` to make the sink global.

```haskell
globalSinkRef :: IORef (Sink Action)
globalSinkRef = unsafePerformIO $ newIORef (\_ -> pure ())

update InitGlobalSink m = 
  effectSub m $ \sink -> 
    m <# liftIO (writeIORef globalSinkRef sink)
```

Then you can just do `readIORef globalSinkRef` to get the sink from any IO action w/o polluting your model. Hope this helps.

Lastly, `IORef` should be fine over `MVar`, since the concurrency is handled internally, shouldn't need `MVar` necessarily.

TBH, we could add this to the library and users could make use of it exactly for circumstances like this.

**Comment by dmjio** [comment]
https://github.com/dmjio/miso/pull/751

**Comment by functora** [comment]
Thanks @dmjio !

**Comment by dmjio** [comment]
Yea let me know how it works out for you
